[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[env]
PORT = "8080"
NODE_ENV = "production"

[http]
compression = true
routes = [
    { path = "/api/*", destination = "backend" },
    { path = "/*", destination = "frontend" }
]
